In [2]:
%matplotlib inline
import matplotlib.image as mpimg
import numpy as np
import matplotlib.pyplot as plt
import os,sys
from PIL import Image
from proj2_helpers import *
from sklearn import linear_model
from sklearn.preprocessing import PolynomialFeatures
from helpers_CNN import *

In [3]:
import time
import torch
from torch import nn, optim
import torchvision

import sys
sys.path.append("..") 
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

print(torch.__version__)
print(torchvision.__version__)
print(device)
import torchvision.transforms as transforms

1.3.1
0.2.1
cpu


In [4]:
def train_ch5(net, train_iter, test_iter, batch_size, optimizer, device, num_epochs):
    net = net.to(device)
    print("training on ", device)
    loss = torch.nn.CrossEntropyLoss()
    batch_count = 0
    for epoch in range(num_epochs):
        train_l_sum, train_acc_sum, n, start = 0.0, 0.0, 0, time.time()
        for X, y in train_iter:
            X = X.to(device)
            y = y.to(device)
            y_hat = net(X)
            l = loss(y_hat, y)
            optimizer.zero_grad()
            l.backward()
            optimizer.step()
            train_l_sum += l.cpu().item()
            train_acc_sum += (y_hat.argmax(dim=1) == y).sum().cpu().item()
            n += y.shape[0]
            batch_count += 1
        test_acc = evaluate_accuracy(test_iter, net)
        print('epoch %d, loss %.4f, train acc %.3f, test acc %.3f, time %.1f sec'
              % (epoch + 1, train_l_sum / batch_count, train_acc_sum / n, test_acc, time.time() - start))

In [6]:
def load_data_fashion_mnist(batch_size, root='~/Datasets/FashionMNIST'):
     """Download the fashion mnist dataset and then load into memory."""
    transform = transforms.ToTensor()
    mnist_train = torchvision.datasets.FashionMNIST(root=root, train=True, download=True, transform=transform)
    mnist_test = torchvision.datasets.FashionMNIST(root=root, train=False, download=True, transform=transform)
    if sys.platform.startswith('win'):
        num_workers = 0  # 0表示不用额外的进程来加速读取数据
    else:
        num_workers = 4
    train_iter = torch.utils.data.DataLoader(mnist_train, batch_size=batch_size, shuffle=True, num_workers=num_workers)
    test_iter = torch.utils.data.DataLoader(mnist_test, batch_size=batch_size, shuffle=False, num_workers=num_workers)

    return train_iter, test_iter

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 3)

In [7]:
root='~/Datasets/FashionMNIST'
transform = transforms.ToTensor()
mnist_train = torchvision.datasets.FashionMNIST(root=root, train=True, download=True, transform=transform)
mnist_test = torchvision.datasets.FashionMNIST(root=root, train=False, download=True, transform=transform)

In [8]:
mnist_train

Dataset FashionMNIST
    Number of datapoints: 60000
    Split: train
    Root Location: C:\Users\wangz/Datasets/FashionMNIST
    Transforms (if any): ToTensor()
    Target Transforms (if any): None

In [13]:
X,y = mnist_train[1]

In [15]:
X.numpy().shape

(1, 28, 28)

In [18]:
y

tensor(0)

In [19]:
import torch

In [30]:
test = torch.tensor([[1,2,3],[4,5,6]])

In [32]:
index = torch.tensor([1,2,0])
test_new = test[:,index]

In [35]:
test

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
test.numpy()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [34]:
test_new

tensor([[2, 3, 1],
        [5, 6, 4]])